<?php
/**
 * BlincPartnersApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BlincPartners
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Blinc Partner API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BlincPartners\Test\Api;

use \BlincPartners\Configuration;
use \BlincPartners\ApiException;
use \BlincPartners\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BlincPartnersApiTest Class Doc Comment
 *
 * @category Class
 * @package  BlincPartners
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BlincPartnersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createSession
     *
     * .
     *
     */
    public function testCreateSession()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPayment
     *
     * .
     *
     */
    public function testGetPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
